# Assignment 1- NumPy Hands-on #

## Part A ##

## Import Modules ##

In [22]:
import numpy as np

## Array Creation ##

In [57]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int64)

## 1.MIN ##

In [58]:
a.min()


1

In [59]:
a.min(axis=0)

array([1, 2, 3])

In [60]:
a.min(axis=1)

array([1, 4, 7])

## 2.MAX ##

In [27]:
a.max()

9

In [28]:
a.max(axis=0)

array([7, 8, 9])

In [29]:
a.max(axis=1)

array([3, 6, 9])

## 3.MEAN ##

In [30]:
a.mean()

5.0

In [31]:
a.mean(axis=0)

array([ 4.,  5.,  6.])

In [32]:
a.mean(axis=1)

array([ 2.,  5.,  8.])

## 4.ARGMIN ##

In [66]:
np.argmin(a)

0

## 5.ARGMAX ##

In [67]:
np.argmax(a)

8

## 6.LINALG.SOLVE ##

In [63]:
c=np.array([[3,1],[1,2]])
v=np.array([9,8])
x=np.linalg.solve(c,v)
x

array([ 2.,  3.])

## 7.FLATTEN ##

In [69]:
a.flatten(order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a.flatten(order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

## 8.RAVEL ##

In [35]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 9.DOT ##

In [36]:
b=np.array([[1,0,0],[0,1,0],[0,0,1]])
np.dot(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 10.* for Matrix (Element wise multiplication) ##

In [37]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
a*c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## 11.Arange Followed By Reshape ##

In [38]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 12.Identity / Eye ##

In [40]:
np.identity(3,dtype=np.int64)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
np.eye(3,3,dtype=np.int64)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 13.SUM ##

In [42]:
np.sum(a,axis=0)

array([12, 15, 18])

In [43]:
np.sum(a,axis=1)

array([ 6, 15, 24])

## 14.DIAG ##

In [44]:
np.diagonal(a)


array([1, 5, 9])

In [45]:
np.diagonal(a,1)

array([2, 6])

## TRIL/TRIU ##

 ## TRIL ##

In [46]:
np.tril(a,-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [47]:
np.tril(a,0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [48]:
np.tril(a,1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.tril(a,2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## TRIU ##

In [50]:
np.triu(a,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9]])

In [51]:
np.triu(a,0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [52]:
np.triu(a,1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])